name: Build And Push Docker Image

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: build-and-push-docker-image
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        env:
          OCD_ENGINE: docker
        run: ./build-image.sh --push
